---
  - hosts: all
    sudo: True
    roles:
      - { role: users, tags: 'users' }
      - { role: network, tags: 'network' }
      - { role: services, tags: 'services' }
      - { role: cldemo, tags: 'cldemo' }
