# create cumulus user
- name: create cumulus
  user: name=cumulus generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

# add motd
- name: configure /etc/motd
  copy: src=motd dest=/etc/motd

# add colors to bash
- name: add bash colors for cumulus
  copy: src=bashrc dest=/home/cumulus/.bashrc

- name: add bash colors for root
  copy: src=bashrc dest=/root/.bashrc

- name: add bash colors for vagrant
  copy: src=bashrc_vagrant dest=/home/vagrant/.bashrc

# update apt source list
- name: install apt source list
  template: src=apt_sources.list.j2  dest=/etc/apt/sources.list

# install ansible
#- name: install git
#  apt: name={{item}} state=present
#  with_items:
#    - software-properties-common

#- name: add ansible repo
#  apt_repository: repo={{item}}
#  with_items:
#    - ppa:ansible/ansible

- name: update apt cache
  apt: update_cache=yes

#- name: install ansible
#  apt: pkg=ansible state=present

# install base packages
- name: install base packages
  apt: name={{item}} state=present
  with_items:
    - git
    - curl
    - man
    - bash-completion
    - python-paramiko
    - python-pip

- name: download ansible 2.0.2.0
  unarchive: src=http://releases.ansible.com/ansible/ansible-2.0.2.0-0.4.rc4.tar.gz dest=/home/vagrant/ copy=no

- name: ansible setup.py build
  shell: /usr/bin/python /home/vagrant/ansible-2.0.2.0/setup.py build
  become: true
  become_method: sudo
  args:
    chdir: /home/vagrant/ansible-2.0.2.0

- name: ansible setup.py install
  shell: /usr/bin/python /home/vagrant/ansible-2.0.2.0/setup.py install
  become: true
  become_method: sudo
  args:
    chdir: /home/vagrant/ansible-2.0.2.0

- name: create ansible symlinks
  file: src=/usr/local/bin/{{ item }} dest=/usr/bin/{{ item }} state=link
  with_items:
    - ansible
    - ansible-playbook
    - ansible-doc

- name: remove ansible directory
  file: path=/home/vagrant/ansible-2.0.2.0 state=absent

- name: git clone cldemo-ansible
  git: repo=https://github.com/sciarrilli/nick-cldemo-ansible.git dest=/home/cumulus/nick-cldemo-ansible
  become: yes
  become_user: cumulus
