# create cumulus user
- name: create cumulus
  user: name=cumulus generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

# add motd
- name: configure /etc/motd
  copy: src=motd dest=/etc/motd

# add colors to bash
- name: add bash colors for cumulus
  copy: src=bashrc dest=/home/cumulus/.bashrc

- name: add bash colors for root
  copy: src=bashrc dest=/root/.bashrc

- name: add bash colors for vagrant
  copy: src=bashrc dest=/home/vagrant/.bashrc

# update apt source list
- name: install apt source list
  template: src=apt_sources.list.j2  dest=/etc/apt/sources.list

# install ansible
#- name: install git
#  apt: name={{item}} state=present
#  with_items:
#    - software-properties-common

- name: add ansible repo
  apt_repository: repo={{item}}
  with_items:
    - ppa:ansible/ansible

- name: update apt cache
  apt: update_cache=yes

- name: install ansible
  apt: pkg=ansible state=present

# install base packages
- name: install base packages
  apt: name={{item}} state=present
  with_items:
    - git
    - curl
    - man
    - bash-completion
    - python-paramiko

- name: git clone cldemo-indie
  git: repo=https://github.com/sciarrilli/nick-cldemo-ebgp.git dest=/home/cumulus/nick-cldemo-ebgp
  become: yes
  become_user: cumulus
